/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ashan Pro
 */
public class cus extends javax.swing.JFrame {

    
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    String nice = "munchee nice";
    String cola = "cocacola";
    String mari = "maliban mari";
    String tipitip = "tipitip";
    
    double priceOfNice = 50;
    double priceOfCola = 100;
    double priceOfMari = 50;
    double priceOfTipiTip = 30;
    
    /**
     * Creates new form cus
     */
    public cus() {
         con = DBconnect.connect();
        //page eka lord weddi mulin krna ewa methna dnne
        initComponents();
        //table lord krna eka
        tableload();
    }
    
    
     public void tableload()
    {
        
        try {
            String sql = "SELECT cusid,name,contc,gend,prod,qty,amunt,dis,totl from customer";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            ctable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepnel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        cqtybox = new javax.swing.JTextField();
        cnamebox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        contbox = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Camountbox = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        cdiscountbox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        ctotbox = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        cgenbox = new javax.swing.JComboBox<>();
        cprintbtn = new javax.swing.JButton();
        caddbtn = new javax.swing.JButton();
        cupdatebtn = new javax.swing.JButton();
        cdelbtn = new javax.swing.JButton();
        cclerbtn = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cprodbox = new javax.swing.JComboBox<>();
        cidbox1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepnel.setBackground(new java.awt.Color(23, 35, 51));
        sidepnel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_home_48px_1.png"))); // NOI18N
        sidepnel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_gender_neutral_user_48px.png"))); // NOI18N
        sidepnel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 52, 40));

        jButton3.setText("Payroll");
        sidepnel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 417, 90, -1));

        jButton4.setText("Home");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 20));

        jButton5.setText("Customer");
        sidepnel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        jButton6.setText("Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 20));

        jButton7.setText("Employee");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 20));

        jButton8.setText("Tranceport");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_user_48px.png"))); // NOI18N
        sidepnel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 52, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_administrator_male_48px.png"))); // NOI18N
        sidepnel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 52, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_car_48px.png"))); // NOI18N
        sidepnel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_money_64px.png"))); // NOI18N
        sidepnel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 40, 30));

        getContentPane().add(sidepnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 140, 640));

        jPanel2.setBackground(new java.awt.Color(71, 120, 190));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sbox.setBackground(new java.awt.Color(123, 156, 208));
        sbox.setBorder(null);
        sbox.setPreferredSize(new java.awt.Dimension(6, 23));
        sbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sboxActionPerformed(evt);
            }
        });
        jPanel2.add(sbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 17, 144, -1));

        jButton1.setText("Serch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(604, 17, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_close_window_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(899, 1, 30, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 930, 50));

        jPanel3.setBackground(new java.awt.Color(71, 120, 190));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 153, 153));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_user_48px.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Customer Management");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 4, 310, 60));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 10));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Customer id");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        cqtybox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cqtyboxActionPerformed(evt);
            }
        });
        jPanel3.add(cqtybox, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 60, 20));
        jPanel3.add(cnamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 255));
        jLabel17.setText("Name");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel3.add(contbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 255));
        jLabel18.setText("Contact number");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 255, 255));
        jLabel19.setText("Qty");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));
        jPanel3.add(Camountbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 270, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 255));
        jLabel20.setText("Amount");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, -1, -1));
        jPanel3.add(cdiscountbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 430, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Discount");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));
        jPanel3.add(ctotbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 480, 270, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 255, 255));
        jLabel22.setText("Total Amount");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 490, -1, -1));

        cgenbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(cgenbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 130, -1));

        cprintbtn.setText("Print");
        jPanel3.add(cprintbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 540, -1, -1));

        caddbtn.setText("Add");
        caddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddbtnActionPerformed(evt);
            }
        });
        jPanel3.add(caddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 540, -1, -1));

        cupdatebtn.setText("Update");
        cupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(cupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 540, -1, -1));

        cdelbtn.setText("Delete");
        cdelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdelbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cdelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 540, -1, -1));

        cclerbtn.setText("Clear");
        cclerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cclerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 540, -1, -1));

        jButton9.setText("Calculate");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 390, -1, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 255, 255));
        jLabel23.setText("Gender");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));

        cprodbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Munchee Nice", "Cocacola", "Maliban Mari", "tipitip " }));
        jPanel3.add(cprodbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 130, -1));

        cidbox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cidbox1ActionPerformed(evt);
            }
        });
        jPanel3.add(cidbox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 255, 255));
        jLabel24.setText("Product");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 420, 580));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 500, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        home h1 = new home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void sboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sboxActionPerformed

    private void cqtyboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cqtyboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cqtyboxActionPerformed

    private void caddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddbtnActionPerformed
       
        //data base add part
        String cid = cqtybox.getText();
        String cname = cnamebox.getText();
        String ccont = contbox.getText();
        String cgen = cgenbox.getSelectedItem().toString();
        String cpro = cprodbox.getSelectedItem().toString();
        String cqty = cqtybox.getText();
        String camunt = Camountbox.getText();
        String cdis = cdiscountbox.getText();
        String ctot = ctotbox.getText();
        
        try {
             String q = "INSERT INTO customer (name,contc,gend,prod,qty,amunt,dis,totl) values ('"+ cname +"','"+ ccont +"','"+ cgen +"','"+ cpro +"','"+ cqty +"','"+ camunt +"','"+ cdis +"','"+ ctot +"')";
             pst = con.prepareStatement(q);
             pst.execute();//exicute krnwa database ekaata
            //lord table
             tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_caddbtnActionPerformed

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:
        
         //value eka select krma box walta ynna
        int r = ctable.getSelectedRow();
        
        String id = ctable.getValueAt(r, 0).toString();
        String name = ctable.getValueAt(r, 1).toString();
        String phone = ctable.getValueAt(r, 2).toString();
        String gen = ctable.getValueAt(r, 3).toString();
        String pro = ctable.getValueAt(r, 4).toString();
        String qty = ctable.getValueAt(r, 5).toString();
         String amt = ctable.getValueAt(r, 6).toString();
          String dis = ctable.getValueAt(r, 7).toString();
           String tot = ctable.getValueAt(r, 8).toString();
           
        cidbox1.setText(id);
        cnamebox.setText(name);
        contbox.setText(phone);
        cgenbox.setSelectedItem(gen);
        cprodbox.setSelectedItem(pro);
        cqtybox.setText(qty);
        Camountbox.setText(amt);
        cdiscountbox.setText(dis);
        ctotbox.setText(tot);
    }//GEN-LAST:event_ctableMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void cidbox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cidbox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cidbox1ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        sup s1 = new sup();
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        Emply e1 = new Emply();
        e1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        trance t1 = new trance();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void cupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdatebtnActionPerformed
        // TODO add your handling code here:
         int x = JOptionPane.showConfirmDialog(null, "Do you really want to update");
       //update krna oneda ahnwa 
       if(x==0)
        {
            String id = cidbox1.getText();
            String name = cnamebox.getText();
            String phone = contbox.getText();
            String gen = cgenbox.getSelectedItem().toString();
            String pro = cprodbox.getSelectedItem().toString();
            String qty = cqtybox.getText();
            String amt = Camountbox.getText();
            String dis = cdiscountbox.getText();
            String tot = ctotbox.getText();
            
           
           String sql = "UPDATE customer SET name = '"+ name +"' , contc = '"+ phone +"' , gend = '"+ gen +"' , prod = '"+ pro +"' , qty = '"+ qty +"' , amunt = '"+ amt +"' , dis = '"+ dis +"' , totl = '"+ tot +"' where cusid = '"+ id +"'";
            
            //loku wedak krddi try cacach ekk athulta danwa
            try {
                 pst = con.prepareStatement(sql);
                 pst.execute();
                 
                  tableload();
                 
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cupdatebtnActionPerformed

    private void cdelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdelbtnActionPerformed
        // TODO add your handling code here:
        
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this");
       //update krna oneda ahnwa 
       if(x==0)
        {
            String id = cidbox1.getText();
            
            
            String sql = "DELETE from customer where cusid = '"+ id +"'";
            
            //loku wedak krddi try cacach ekk athulta danwa
            try {
                 pst = con.prepareStatement(sql);
                 pst.execute();
                 tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cdelbtnActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        
          
        String prodName = cprodbox.getSelectedItem().toString().toLowerCase();
        double prodPrice = 0;
        double discountPer = 5;
        int itemQty = Integer.parseInt(cqtybox.getText());
        double initAmount;
        double discountAmount;
        double totalAmount;
        
        if( prodName.equals(nice.toLowerCase()) ){
            prodPrice = priceOfNice;
        }
        else if(prodName.equals(cola.toLowerCase())){
            prodPrice = priceOfCola;
        }
        else if(prodName.equals(mari.toLowerCase())){
            prodPrice = priceOfMari;
        }
        else if(prodName.equals(tipitip.toLowerCase())){
            prodPrice = priceOfTipiTip;
        }
        
        initAmount = prodPrice * itemQty;
        
        discountAmount = discountPer / 100 * initAmount;
        
        totalAmount = initAmount - discountAmount;
        
        Camountbox.setText(String.valueOf(initAmount));
        cdiscountbox.setText(String.valueOf(discountAmount));
        ctotbox.setText(String.valueOf(totalAmount));
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         String name = sbox.getText();
        
          String sql = " Select cusid, name,contc,gend,prod,qty,amunt,dis,totl from customer where name LIKE '%"+ name +"%'";
          
           try {
                 pst = con.prepareStatement(sql);
                 rs = pst.executeQuery();
                 
                 ctable.setModel(DbUtils.resultSetToTableModel(rs));
                
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cclerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclerbtnActionPerformed
        // TODO add your handling code here:
        
        cidbox1.setText("");
        cnamebox.setText("");
        contbox.setText("");
        cgenbox.setSelectedItem("");
        cprodbox.setSelectedItem("");
        cqtybox.setText("");
        Camountbox.setText("");
        cdiscountbox.setText("");
        ctotbox.setText("");
    }//GEN-LAST:event_cclerbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cus.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cus().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Camountbox;
    private javax.swing.JButton caddbtn;
    private javax.swing.JButton cclerbtn;
    private javax.swing.JButton cdelbtn;
    private javax.swing.JTextField cdiscountbox;
    private javax.swing.JComboBox<String> cgenbox;
    private javax.swing.JTextField cidbox1;
    private javax.swing.JTextField cnamebox;
    private javax.swing.JTextField contbox;
    private javax.swing.JButton cprintbtn;
    private javax.swing.JComboBox<String> cprodbox;
    private javax.swing.JTextField cqtybox;
    private javax.swing.JTable ctable;
    private javax.swing.JTextField ctotbox;
    private javax.swing.JButton cupdatebtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField sbox;
    private javax.swing.JPanel sidepnel;
    // End of variables declaration//GEN-END:variables
}
