/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ashan Pro
 */
public class Emply extends javax.swing.JFrame {

   
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs= null;
    
    /**
     * Creates new form Emply
     */
    public Emply() {
        initComponents();
        con = DBconnect.connect();
        //table call
        tableload();
    }
    
     public void tableload()
    {
        
        try {
            String sql = "SELECT eid,ename,econtac,email,egen,jobti,nic from employ";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            ctable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepnel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel19 = new javax.swing.JLabel();
        eidbox = new javax.swing.JTextField();
        enamebox = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        econtlbox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        enicbox = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        eemailbox = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        egenbox = new javax.swing.JComboBox<>();
        cprintbtn = new javax.swing.JButton();
        caddbtn = new javax.swing.JButton();
        cupdatebtn = new javax.swing.JButton();
        cdelbtn = new javax.swing.JButton();
        cclerbtn = new javax.swing.JButton();
        jLabel25 = new javax.swing.JLabel();
        ejobbox = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepnel2.setBackground(new java.awt.Color(23, 35, 51));
        sidepnel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_home_48px_1.png"))); // NOI18N
        sidepnel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 50, 30));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_gender_neutral_user_48px.png"))); // NOI18N
        sidepnel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 52, 40));

        jButton7.setText("Payroll");
        sidepnel2.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 417, 90, -1));

        jButton8.setText("Home");
        jButton8.setOpaque(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        sidepnel2.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 80, 20));

        jButton9.setText("Customer");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        sidepnel2.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        jButton10.setText("Supplier");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        sidepnel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 20));

        jButton11.setText("Employee");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        sidepnel2.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 20));

        jButton12.setText("Tranceport");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        sidepnel2.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 20));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_user_48px.png"))); // NOI18N
        sidepnel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 52, 30));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_administrator_male_48px.png"))); // NOI18N
        sidepnel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 52, 30));

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_car_48px.png"))); // NOI18N
        sidepnel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_money_64px.png"))); // NOI18N
        sidepnel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 40, 30));

        getContentPane().add(sidepnel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 140, 600));

        jPanel2.setBackground(new java.awt.Color(71, 120, 190));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sbox.setBackground(new java.awt.Color(123, 156, 208));
        sbox.setBorder(null);
        sbox.setPreferredSize(new java.awt.Dimension(6, 23));
        sbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sboxActionPerformed(evt);
            }
        });
        jPanel2.add(sbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 15, 144, -1));

        jButton1.setText("Serch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 15, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_close_window_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 31, 30));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 930, 50));

        jPanel3.setBackground(new java.awt.Color(71, 120, 190));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 102));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_gender_neutral_user_48px.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 80, 70));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Employee Management");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 4, 310, 60));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 10));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(153, 255, 255));
        jLabel19.setText("Employee id");
        jPanel3.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        eidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidboxActionPerformed(evt);
            }
        });
        jPanel3.add(eidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 30));
        jPanel3.add(enamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 255));
        jLabel20.setText("Name");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel3.add(econtlbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Phone Number");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 255, 255));
        jLabel22.setText("Job Title");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, -1));
        jPanel3.add(enicbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 380, 270, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 255, 255));
        jLabel23.setText("NIC");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 390, -1, -1));
        jPanel3.add(eemailbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 270, 30));

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(153, 255, 255));
        jLabel24.setText("Email");
        jPanel3.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        egenbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        jPanel3.add(egenbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 130, -1));

        cprintbtn.setText("Print");
        jPanel3.add(cprintbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        caddbtn.setText("Add");
        caddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddbtnActionPerformed(evt);
            }
        });
        jPanel3.add(caddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        cupdatebtn.setText("Update");
        cupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(cupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        cdelbtn.setText("Delete");
        cdelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdelbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cdelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        cclerbtn.setText("Clear");
        cclerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cclerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(153, 255, 255));
        jLabel25.setText("Gender");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 300, -1, -1));

        ejobbox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manager", "Casier", "Driver" }));
        jPanel3.add(ejobbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 340, -1, -1));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 420, 540));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 500, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        home h1 = new home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void sboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidboxActionPerformed

    private void caddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddbtnActionPerformed
        // TODO add your handling code here:

        //data base add part
        String eid = eidbox.getText();
        String ename = enamebox.getText();
        String econt = econtlbox.getText();
        String email = eemailbox.getText();
        String egen = egenbox.getSelectedItem().toString();
        String ejob = ejobbox.getSelectedItem().toString();
        String enic = enicbox.getText();

        try {
            String q = "INSERT INTO employ (ename,econtac,email,egen,jobti,nic) values ('"+ ename +"','"+ econt +"','"+ email +"','"+ egen +"','"+ ejob +"','"+ enic +"')";
            pst = con.prepareStatement(q);
            pst.execute();//exicute krnwa database ekaata
            //lord table
            tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_caddbtnActionPerformed

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:
        
//value eka select krma box walta ynna
        int r = ctable.getSelectedRow();

        String id = ctable.getValueAt(r, 0).toString();
        String name = ctable.getValueAt(r, 1).toString();
        String phone = ctable.getValueAt(r, 2).toString();
        String mail = ctable.getValueAt(r, 3).toString();
        String gen = ctable.getValueAt(r, 4).toString();
        String job = ctable.getValueAt(r, 5).toString();
        String nic = ctable.getValueAt(r, 6).toString();
        
        eidbox.setText(id);
        enamebox.setText(name);
        econtlbox.setText(phone);
        eemailbox.setText(mail);
        egenbox.setSelectedItem(gen);
        ejobbox.setSelectedItem(job);
        enicbox.setText(nic);
        
        
    }//GEN-LAST:event_ctableMouseClicked

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        cus c1 = new cus();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        sup s1 = new sup();
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
       
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
         //page eka lord krnna cunstrutor ekk hdghda
        trance t1 = new trance();
        t1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton12ActionPerformed

    private void cupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdatebtnActionPerformed
        // TODO add your handling code here:
        //update krddi ahana massage eke
       int x = JOptionPane.showConfirmDialog(null, "Do you really want to update");
       //update krna oneda ahnwa 
       if(x==0)
        {
            String id = eidbox.getText();
            String name = enamebox.getText();
            String phone = econtlbox.getText();
            String email = eemailbox.getText();
            String gen = egenbox.getSelectedItem().toString();
            String job = ejobbox.getSelectedItem().toString();
            String nic = enicbox.getText();
            
            String sql = "UPDATE employ SET ename = '"+ name +"', econtac = '"+ phone +"', email = '"+ email +"', egen = '"+ gen +"', jobti = '"+ job +"', nic = '"+ nic +"' where eid = '"+ id +"'";
            
            //loku wedak krddi try cacach ekk athulta danwa
            try {
                 pst = con.prepareStatement(sql);
                 pst.execute();
                 tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cupdatebtnActionPerformed

    private void cdelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdelbtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this");
       //update krna oneda ahnwa 
       if(x==0)
        {
            String id = eidbox.getText();
            
            
            String sql = "DELETE from employ where eid = '"+ id +"'";
            
            //loku wedak krddi try cacach ekk athulta danwa
            try {
                 pst = con.prepareStatement(sql);
                 pst.execute();
                 tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cdelbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String name = sbox.getText();
        
          String sql = " Select eid, ename,econtac,email,egen,jobti,nic from employ where ename LIKE '%"+ name +"%'";
          
           try {
                 pst = con.prepareStatement(sql);
                 rs = pst.executeQuery();
                 
                 ctable.setModel(DbUtils.resultSetToTableModel(rs));
                
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cclerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclerbtnActionPerformed
        // TODO add your handling code here:
         eidbox.setText("");
        enamebox.setText("");
        econtlbox.setText("");
        eemailbox.setText("");
        egenbox.setSelectedItem("");
        ejobbox.setSelectedItem("");
        enicbox.setText("");
        
    }//GEN-LAST:event_cclerbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emply.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emply().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton caddbtn;
    private javax.swing.JButton cclerbtn;
    private javax.swing.JButton cdelbtn;
    private javax.swing.JButton cprintbtn;
    private javax.swing.JTable ctable;
    private javax.swing.JButton cupdatebtn;
    private javax.swing.JTextField econtlbox;
    private javax.swing.JTextField eemailbox;
    private javax.swing.JComboBox<String> egenbox;
    private javax.swing.JTextField eidbox;
    private javax.swing.JComboBox<String> ejobbox;
    private javax.swing.JTextField enamebox;
    private javax.swing.JTextField enicbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField sbox;
    private javax.swing.JPanel sidepnel2;
    // End of variables declaration//GEN-END:variables
}
