/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//id databse is not auto increment
package swing;

import database.DBconnect;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author Ashan Pro
 */
public class payroll extends javax.swing.JFrame {

    
     Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs= null;
   
    /**
     * Creates new form payroll
     */
    public payroll() {
        initComponents();
         con = DBconnect.connect();
        //table call
        tableload();
    }
public void tableload()
    {
        
        try {
            String sql = "SELECT empid,ename,stdate,enddate,sal,ot,advance from payrol";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            
            ctable.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e) {
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidepnel = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        sbox = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        eidbox = new javax.swing.JTextField();
        endbox = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        enamebox = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        otbox = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cprintbtn = new javax.swing.JButton();
        caddbtn = new javax.swing.JButton();
        cupdatebtn = new javax.swing.JButton();
        cdelbtn = new javax.swing.JButton();
        cclerbtn = new javax.swing.JButton();
        salbox = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        strbox = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        adbox = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ctable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidepnel.setBackground(new java.awt.Color(23, 35, 51));
        sidepnel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_home_48px_1.png"))); // NOI18N
        sidepnel.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 50, 30));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_gender_neutral_user_48px.png"))); // NOI18N
        sidepnel.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 52, 40));

        jButton3.setText("Payroll");
        sidepnel.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 417, 90, -1));

        jButton4.setText("Home");
        jButton4.setOpaque(false);
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 90, 20));

        jButton5.setText("Customer");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 20));

        jButton6.setText("Supplier");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 90, 20));

        jButton7.setText("Employee");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        sidepnel.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, 90, 20));

        jButton8.setText("Tranceport");
        sidepnel.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 90, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_user_48px.png"))); // NOI18N
        sidepnel.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 52, 30));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_administrator_male_48px.png"))); // NOI18N
        sidepnel.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 52, 30));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_car_48px.png"))); // NOI18N
        sidepnel.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 60, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_money_64px.png"))); // NOI18N
        sidepnel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 410, 40, 30));

        getContentPane().add(sidepnel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -4, 140, 600));

        jPanel2.setBackground(new java.awt.Color(71, 120, 190));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 1, true));

        sbox.setBackground(new java.awt.Color(123, 156, 208));
        sbox.setBorder(null);
        sbox.setPreferredSize(new java.awt.Dimension(6, 23));
        sbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sboxActionPerformed(evt);
            }
        });

        jButton1.setText("Serch");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_close_window_30px.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(457, Short.MAX_VALUE)
                .addComponent(sbox, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(231, 231, 231)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 930, 50));

        jPanel3.setBackground(new java.awt.Color(71, 120, 190));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pic/icons8_money_64px.png"))); // NOI18N
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 80, 70));

        jLabel3.setFont(new java.awt.Font("Segoe Print", 2, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Payroll Management");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 255)));
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 4, 310, 60));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 50, 280, 10));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 70));

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(153, 255, 255));
        jLabel16.setText("Employee id");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        eidbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eidboxActionPerformed(evt);
            }
        });
        jPanel3.add(eidbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 130, 30));
        jPanel3.add(endbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 190, 80, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(153, 255, 255));
        jLabel17.setText("TO");
        jPanel3.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, -1, -1));

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(153, 255, 255));
        jLabel18.setText("Basic salary");
        jPanel3.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, -1, -1));
        jPanel3.add(enamebox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 140, 270, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(153, 255, 255));
        jLabel20.setText("Name");
        jPanel3.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));
        jPanel3.add(otbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 270, 30));

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(153, 255, 255));
        jLabel21.setText("Ot hours");
        jPanel3.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, -1, -1));

        cprintbtn.setText("Print");
        jPanel3.add(cprintbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 500, -1, -1));

        caddbtn.setText("Add");
        caddbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caddbtnActionPerformed(evt);
            }
        });
        jPanel3.add(caddbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, -1, -1));

        cupdatebtn.setText("Update");
        cupdatebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cupdatebtnActionPerformed(evt);
            }
        });
        jPanel3.add(cupdatebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 500, -1, -1));

        cdelbtn.setText("Delete");
        cdelbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cdelbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cdelbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 500, -1, -1));

        cclerbtn.setText("Clear");
        cclerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cclerbtnActionPerformed(evt);
            }
        });
        jPanel3.add(cclerbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 500, -1, -1));
        jPanel3.add(salbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 270, 30));

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(153, 255, 255));
        jLabel22.setText("Start date");
        jPanel3.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, -1, -1));
        jPanel3.add(strbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 80, 30));

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(153, 255, 255));
        jLabel23.setText("Advance");
        jPanel3.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, -1, -1));
        jPanel3.add(adbox, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 360, 270, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 420, 540));

        jPanel5.setBackground(new java.awt.Color(0, 153, 204));

        ctable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        ctable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ctableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ctable);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 50, 500, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        //page eka lord krnna cunstrutor ekk hdghda
        home h1 = new home();
        h1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        //page eka lord krnna cunstrutor ekk hdghda
        cus c1 = new cus();
        c1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        //page eka lord krnna cunstrutor ekk hdghda
        sup s1 = new sup();
        s1.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        //page eka lord krnna cunstrutor ekk hdghda
        //page eka lord krnna cunstrutor ekk hdghda
        Emply e1 = new Emply();
        e1.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jButton7ActionPerformed

    private void sboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sboxActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void eidboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eidboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_eidboxActionPerformed

    private void caddbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caddbtnActionPerformed
        // TODO add your handling code here:

        //data base add part
        String eid = eidbox.getText();
        String ename = enamebox.getText();
        String str = strbox.getText();
        String strend = endbox.getText();
        String esal = salbox.getText();
     
        String eot = otbox.getText();
        String eadd = adbox.getText();

        try {
            String q = "INSERT INTO payrol (empid,ename,stdate,enddate,sal,ot,advance) values ('"+ eid +"','"+ ename +"','"+ str +"','"+ strend +"','"+ esal +"','"+ eot +"','"+ eadd +"')";
            pst = con.prepareStatement(q);
            pst.execute();//exicute krnwa database ekaata
            //lord table
            tableload();
        } catch (Exception e) {
        }
    }//GEN-LAST:event_caddbtnActionPerformed

    private void cupdatebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cupdatebtnActionPerformed
        // TODO add your handling code here:
        int x = JOptionPane.showConfirmDialog(null, "Do you really want to update");
        //update krna oneda ahnwa
        if(x==0)
        {
        String eid = eidbox.getText();
        String ename = enamebox.getText();
        String str = strbox.getText();
        String strend = endbox.getText();
        String esal = salbox.getText();
     
        String eot = otbox.getText();
        String eadd = adbox.getText();

            String sql = "UPDATE payrol SET ename = '"+ ename +"' , stdate = '"+ str +"' , enddate = '"+ strend +"' , sal = '"+ esal +"' , ot = '"+ eot +"', advance = '"+ eadd +"' where empid = '"+ eid +"'";

            //loku wedak krddi try cacach ekk athulta danwa
            try {
                pst = con.prepareStatement(sql);
                pst.execute();

                tableload();

            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cupdatebtnActionPerformed

    private void ctableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ctableMouseClicked
        // TODO add your handling code here:
        //value eka select krma box walta ynna
        int r = ctable.getSelectedRow();

        String id = ctable.getValueAt(r, 0).toString();
        String name = ctable.getValueAt(r, 1).toString();
        String str = ctable.getValueAt(r, 2).toString();
        String strend = ctable.getValueAt(r, 3).toString();
        String esal = ctable.getValueAt(r, 4).toString();
        String eot = ctable.getValueAt(r, 5).toString();
        String eadd = ctable.getValueAt(r, 6).toString();
        
        eidbox.setText(id);
        enamebox.setText(name);
        strbox.setText(str);
        endbox.setText(strend);
        salbox.setText(esal);
        otbox.setText(eot);
         adbox.setText(eadd);

    }//GEN-LAST:event_ctableMouseClicked

    private void cdelbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cdelbtnActionPerformed
        // TODO add your handling code here:
          int x = JOptionPane.showConfirmDialog(null, "Do you really want to Delete this");
       //update krna oneda ahnwa 
       if(x==0)
        {
            String id = eidbox.getText();
                 
            String sql = "DELETE from payrol where empid = '"+ id +"'";
            
            //loku wedak krddi try cacach ekk athulta danwa
            try {
                 pst = con.prepareStatement(sql);
                 pst.execute();
                 tableload();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_cdelbtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         String name = sbox.getText();
        
          String sql = " Select empid, ename,stdate,enddate,sal,ot,advance from payrol where ename LIKE '%"+ name +"%'";
          
           try {
                 pst = con.prepareStatement(sql);
                 rs = pst.executeQuery();
                 
                 ctable.setModel(DbUtils.resultSetToTableModel(rs));
                
            } catch (Exception e) {
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cclerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cclerbtnActionPerformed
        // TODO add your handling code here:
        
         eidbox.setText("");
        enamebox.setText("");
        strbox.setText("");
        endbox.setText("");
        salbox.setText("");
        otbox.setText("");
         adbox.setText("");
    }//GEN-LAST:event_cclerbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(payroll.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new payroll().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField adbox;
    private javax.swing.JButton caddbtn;
    private javax.swing.JButton cclerbtn;
    private javax.swing.JButton cdelbtn;
    private javax.swing.JButton cprintbtn;
    private javax.swing.JTable ctable;
    private javax.swing.JButton cupdatebtn;
    private javax.swing.JTextField eidbox;
    private javax.swing.JTextField enamebox;
    private javax.swing.JTextField endbox;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField otbox;
    private javax.swing.JTextField salbox;
    private javax.swing.JTextField sbox;
    private javax.swing.JPanel sidepnel;
    private javax.swing.JTextField strbox;
    // End of variables declaration//GEN-END:variables
}
